/* Local-first itinerary map. Coordinates are supplied by the current trip only.
   Dotted lines show visit order, never a computed road/transit route. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.TripItineraryMap=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const R=6378137,MAX_LAT=85.05112878,REGION_KM=250;
const moduleBase=typeof document!=='undefined'&&document.currentScript?.src?new URL('.',document.currentScript.src).href:'';
const included=x=>x&&!['cancelled','skipped'].includes(x.status);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validCoords=ll=>Array.isArray(ll)&&ll.length===2&&ll.every(Number.isFinite)&&Math.abs(ll[0])<=90&&Math.abs(ll[1])<=180;
const coords=p=>validCoords(p?.ll)?p.ll.slice():null;
const flight=x=>!!(x?.isFlight||['flight','flying','airplane'].includes(x?.travel)||x?.k==='m'&&x.tz!==undefined&&x.endTz!==undefined&&x.tz!==x.endTz);
function distanceKm(a,b){const r=Math.PI/180,dlat=(b[0]-a[0])*r,dlon=(b[1]-a[1])*r,q=Math.sin(dlat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dlon/2)**2;return 6371*2*Math.atan2(Math.sqrt(Math.min(1,q)),Math.sqrt(Math.max(0,1-q)));}
function project(ll){return [R*ll[1]*Math.PI/180,-R*Math.log(Math.tan(Math.PI/4+Math.max(-MAX_LAT,Math.min(MAX_LAT,ll[0]))*Math.PI/360))];}
function unproject(p){return [(2*Math.atan(Math.exp(-p[1]/R))-Math.PI/2)*180/Math.PI,p[0]/R*180/Math.PI];}
function hotelId(trip){return [trip?.hotelPlaceId,trip?.lodgingPlaceId,trip?.hotel?.placeId,'hotel',...Object.keys(trip?.places||{}).filter(id=>trip.places[id]?.isHotel===true)].find(id=>id&&trip?.places?.[id])||null;}
function buildModel(trip,dayId){
 const places=trip?.places||{},items=(trip?.items||[]).filter(x=>x.dayId===dayId&&included(x));
 const hotelPlaceId=hotelId(trip),visits=[],numberByItem=Object.create(null),pointMap=new Map(),missing=[],flights=items.filter(flight),edges=[];
 const addPoint=id=>{if(!id||!places[id]||!coords(places[id]))return null;if(!pointMap.has(id))pointMap.set(id,{id,place:places[id],coords:coords(places[id]),visits:[],isHotel:id===hotelPlaceId});return pointMap.get(id);};
 if(hotelPlaceId)addPoint(hotelPlaceId);
 for(const item of items){if(item.k!=='s'||flight(item)||!item.place)continue;const visit={id:item.id,item,placeId:item.place,place:places[item.place]||{n:item.title},number:visits.length+1};visits.push(visit);numberByItem[item.id]=visit.number;const p=addPoint(item.place);if(p)p.visits.push(visit);else missing.push(visit);}
 for(const item of items){if(item.k!=='m'||flight(item))continue;addPoint(item.from);addPoint(item.to);if(item.from&&item.to&&item.from!==item.to)edges.push({id:item.id,item,kind:'movement',fromPlaceId:item.from,toPlaceId:item.to,fromVisitId:item.fromStopId||null,toVisitId:item.toStopId||null});}
 // Use array order, the same order as the itinerary cards. Do not silently sort.
 for(let n=1;n<visits.length;n++){const a=visits[n-1],b=visits[n],ai=items.indexOf(a.item),bi=items.indexOf(b.item),between=items.slice(ai+1,bi);if(a.placeId===b.placeId||between.some(x=>x.k==='m'||flight(x)))continue;edges.push({id:null,item:null,kind:'sequence',fromPlaceId:a.placeId,toPlaceId:b.placeId,fromVisitId:a.id,toVisitId:b.id,fromNumber:a.number,toNumber:b.number});}
 const points=[...pointMap.values()],regions=[];
 // Separate distant regions instead of fitting international flights as a drive.
 for(const p of points){let matches=regions.filter(g=>g.points.some(q=>distanceKm(p.coords,q.coords)<=REGION_KM));if(!matches.length){regions.push({points:[p]});continue;}const g=matches[0];g.points.push(p);for(const other of matches.slice(1)){g.points.push(...other.points);regions.splice(regions.indexOf(other),1);}}
 regions.forEach((g,i)=>{g.id='region-'+i;g.hasHotel=g.points.some(p=>p.isHotel);g.visitCount=g.points.reduce((n,p)=>n+p.visits.length,0);g.label=g.hasHotel?'숙소 지역':'방문 지역 '+(regions.filter(r=>!r.points.some(p=>p.isHotel)).indexOf(g)+1);for(const p of g.points)p.regionId=g.id;});
 const hotelRegion=regions.find(g=>g.hasHotel),mostVisited=regions.slice().sort((a,b)=>b.visitCount-a.visitCount)[0];
 const defaultRegionId=(hotelRegion?.visitCount?hotelRegion:mostVisited||hotelRegion)?.id||null;
 const remoteEdges=[];for(const e of edges){const a=pointMap.get(e.fromPlaceId),b=pointMap.get(e.toPlaceId);e.from=a||null;e.to=b||null;e.regionId=a&&b&&a.regionId===b.regionId?a.regionId:null;if(a&&b&&!e.regionId)remoteEdges.push(e);}
 return {dayId,day:(trip?.days||[]).find(d=>d.id===dayId),visits,numberByItem,points,pointMap,regions,defaultRegionId,edges,remoteEdges,missing,flights,hotelPlaceId,hotel:hotelPlaceId?places[hotelPlaceId]:null,unlocatedCount:items.filter(x=>x.k==='s'&&!x.place&&!flight(x)).length};
}
function fitView(points,width=640,height=360){const ps=points.map(p=>project(p.coords||p));if(!ps.length)return {cx:0,cy:0,width:2000,height:2000*height/width};const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]);let w=Math.max(900,Math.max(...xs)-Math.min(...xs))*1.4,h=Math.max(650,Math.max(...ys)-Math.min(...ys))*1.6;const ratio=width/Math.max(1,height);if(w/h<ratio)w=h*ratio;else h=w/ratio;return {cx:(Math.max(...xs)+Math.min(...xs))/2,cy:(Math.max(...ys)+Math.min(...ys))/2,width:w,height:h};}
function zoomView(view,factor,anchor={x:.5,y:.5}){const f=Math.max(.08,Math.min(12,factor)),w=Math.max(80,Math.min(4e7,view.width/f)),h=w*view.height/view.width;return {cx:view.cx+(anchor.x-.5)*(view.width-w),cy:view.cy+(anchor.y-.5)*(view.height-h),width:w,height:h};}
function panView(view,dx,dy,width,height){return {...view,cx:view.cx-dx/width*view.width,cy:view.cy-dy/height*view.height};}
// A place focus changes the camera, never the stored point. Keep a user's
// closer zoom, but do not retain an airport-sized overview around a city stop.
function focusView(view,ll,width=640,height=350){const target=fitView([ll],width,height),p=project(ll),w=Math.min(view.width,target.width);return {cx:p[0],cy:p[1],width:w,height:w*height/width};}
// Fixed conservative label boxes make collision choices deterministic without
// moving pins or inventing geographic offsets. Full names remain on buttons.
function labelLayout(candidates,width,height,expanded=false){
 const cap=expanded?155:width>=650?135:width<=350?90:116;
 const boxes=candidates.map((p,index)=>{const w=Math.min(cap,Math.max(44,Array.from(p.label||'').reduce((n,c)=>n+(/[^\x00-\x7F]/.test(c)?10:6),0)+12));return {index,left:p.x-w/2,top:p.y+24,width:w,height:22,visible:false};});
 const markers=candidates.map((p,index)=>{const w=Math.max(48,p.markerWidth||(p.selected?52:48)),h=Math.max(48,p.markerHeight||(p.selected?52:48));return {index,left:p.x-w/2,top:p.y-h/2,width:w,height:h};});
 const overlap=(a,b)=>a.left<b.left+b.width+4&&a.left+a.width+4>b.left&&a.top<b.top+b.height+4&&a.top+a.height+4>b.top;
 const hitsMarker=(a,b)=>a.left<b.left+b.width&&a.left+a.width>b.left&&a.top<b.top+b.height&&a.top+a.height>b.top;
 const chosen=[],order=candidates.map((p,index)=>({index,priority:p.selected?0:p.isHotel?1:p.hasVisits?2:3,order:p.order??index})).sort((a,b)=>a.priority-b.priority||a.order-b.order||a.index-b.index);
 for(const {index} of order){const b=boxes[index],p=candidates[index],pin=markers[index],placements=[{left:b.left,top:b.top}];
  // A selected/hotel name may use another adjacent label position. Only text
  // moves; the geographic pin and its interaction target remain untouched.
  if(p.selected||p.isHotel)placements.push({left:b.left,top:p.y-46},{left:pin.left+pin.width+6,top:p.y-11},{left:pin.left-b.width-6,top:p.y-11});
  for(const position of placements){const candidate={...b,...position};if(candidate.left<4||candidate.left+candidate.width>width-4||candidate.top<4||candidate.top+candidate.height>height-72||chosen.some(a=>overlap(a,candidate))||markers.some(a=>a.index!==index&&hitsMarker(a,candidate)))continue;Object.assign(b,position,{visible:true});chosen.push(b);break;}
 }
 return boxes;
}
function markerGroups(points){const groups=new Map();for(const p of points){const key=p.coords.map(n=>n.toFixed(6)).join(',');if(!groups.has(key))groups.set(key,{coords:p.coords,points:[],visits:[],isHotel:false});const g=groups.get(key);g.points.push(p);g.visits.push(...p.visits);g.isHotel=g.isHotel||p.isHotel;}return [...groups.values()].map(g=>({...g,visits:g.visits.slice().sort((a,b)=>a.number-b.number)}));}
let leafletPromise=null,instanceCount=0;
function loadLeaflet(doc){if(root.L)return Promise.resolve(root.L);if(leafletPromise)return leafletPromise;leafletPromise=new Promise((resolve,reject)=>{let css=doc.querySelector('link[data-itinerary-leaflet]');if(!css){css=doc.createElement('link');css.rel='stylesheet';css.href=moduleBase+'vendor/leaflet/leaflet.css';css.setAttribute('data-itinerary-leaflet','');doc.head.appendChild(css);}const script=doc.createElement('script');script.src=moduleBase+'vendor/leaflet/leaflet.js';script.onload=()=>root.L?resolve(root.L):reject(Error('지도 도구를 불러오지 못했습니다.'));script.onerror=()=>{script.remove();leafletPromise=null;reject(Error('온라인 지도 도구를 불러오지 못했습니다. 오프라인 동선도는 계속 사용할 수 있어요.'));};doc.head.appendChild(script);});return leafletPromise;}
function create(container,initial={}){
 if(!container||!container.ownerDocument)throw Error('지도 표시 영역이 필요합니다.');
 const doc=container.ownerDocument,win=doc.defaultView||root,uid='itinerary-map-'+(++instanceCount),listeners=[],pointers=new Map();
 let options={...initial},model,regionId,view,selectedId=options.selectedId||null,destroyed=false,expanded=false,placeholder=null,oldOverflow='',lastFocus=null,leaflet=null,layerGroup=null,tileLayer=null,online=false,onlineLoading=false,generation=0,gesture=null,dragged=false,ignoreClickUntil=0,resizeObserver=null;
 const shell=doc.createElement('section');shell.className='itinerary-map';shell.setAttribute('aria-label','일정 위치와 방문 순서');container.appendChild(shell);
 const listen=(el,type,fn,opts)=>{el.addEventListener(type,fn,opts);listeners.push(()=>el.removeEventListener(type,fn,opts));};
 const $=s=>shell.querySelector(s),$$=s=>[...shell.querySelectorAll(s)];
 function size(){const rect=$('.imap-stage').getBoundingClientRect();return {width:Math.max(240,rect.width||640),height:Math.max(240,rect.height||350)};}
 function region(){return model.regions.find(g=>g.id===regionId)||null;}
 function setStatus(text){const el=$('.imap-live');if(el)el.textContent=text;}
 function names(p){return p.place?.n||p.id;}
 function titleForGroup(g){const nums=g.visits.map(v=>v.number).join(', '),name=g.points.map(names).join(' / ');return (g.isHotel?'숙소 · ':'')+(nums?nums+'번 방문 · ':'')+name;}
 function button(action,label,inner,extra=''){return `<button type="button" data-map-action="${action}" aria-label="${esc(label)}" ${extra}>${inner||esc(label)}</button>`;}
 function render(){
  const m=model,regionOptions=m.regions.map(r=>`<button type="button" data-map-region="${r.id}" aria-pressed="${r.id===regionId}">${esc(r.label)}${r.visitCount?' · '+r.visitCount+'회':''}</button>`).join('');
  shell.innerHTML=`<div class="imap-heading"><div><span class="imap-eyebrow">DAY ROUTE</span><h3>이날의 위치와 동선</h3><p>${m.visits.length}회 방문 · ${new Set(m.visits.map(v=>v.placeId)).size}곳${m.missing.length?' · 위치 미등록 '+m.missing.length+'회':''}</p></div>${button('expand',expanded?'지도 축소':'지도 크게 보기',expanded?'닫기':'<span aria-hidden="true">⛶</span> 크게')}</div>
   <div class="imap-region-tabs" ${m.regions.length<2?'hidden':''} aria-label="서로 떨어진 지역">${regionOptions}</div>
   <div class="imap-stage" tabindex="0" role="group" aria-label="일정 지도. 방향키로 이동, 더하기 빼기로 확대 축소할 수 있습니다."><svg class="imap-svg" aria-hidden="true"></svg><div class="imap-pins"></div><div class="imap-leaflet" hidden></div><div class="imap-corner-label">오프라인 동선도 <span>저장된 좌표 기준</span></div><div class="imap-north" aria-hidden="true">↑<small>N</small></div><div class="imap-zoom">${button('zoom-in','지도 확대','＋')}${button('zoom-out','지도 축소','−')}</div><div class="imap-mapbar">${button('hotel','숙소 보기','<span aria-hidden="true">⌂</span> 숙소 보기',m.hotel?'':'disabled')}${button('fit','현재 지역 전체 동선 보기','전체 동선')}</div><div class="imap-scale" aria-hidden="true"></div><div class="imap-empty" ${m.points.length?'hidden':''}>${m.visits.length?'위치가 등록된 장소가 없어요':'이 날짜에 표시할 방문 장소가 없어요'}<small>좌표를 임의로 만들지 않습니다</small></div></div>
   <div class="imap-note"><span class="imap-dotted" aria-hidden="true"></span><b>방문 순서 · 실제 도로 경로 아님</b></div>
   <div class="imap-mode"><button type="button" data-map-action="online" aria-pressed="${online}" ${m.points.length?'':'disabled'}>${online?'오프라인 동선도로 전환':'온라인 배경지도 켜기'}</button><span class="imap-mode-note">${online?'OpenStreetMap · 인터넷 필요':'기본 동선도는 인터넷 없이 사용'}</span></div>
   <p class="imap-network-note">온라인 지도는 선택한 영역의 지도 타일을 OpenStreetMap에서 불러옵니다. 제공자에게 접속·표시 영역 정보가 전달되며 통신 데이터가 필요해요. 별도 유료 API 키는 필요 없습니다.</p>
   <div class="imap-hotel-reference" ${m.hotel?'':'hidden'}><span><b>⌂ ${esc(m.hotel?.n||'숙소')}</b><small class="imap-hotel-region"></small></span>${button('hotel-info','숙소 장소 정보 보기','숙소 정보')}</div>
   <div class="imap-selection" aria-live="polite"></div>
   ${m.edges.some(e=>!e.from||!e.to||e.regionId)?`<details class="imap-all-legs"><summary>이날 이동 구간 ${m.edges.filter(e=>!e.from||!e.to||e.regionId).length}개 보기</summary><p>지도에서 짧게 겹친 구간도 여기서 선택할 수 있어요</p>${m.edges.map((e,index)=>({e,index})).filter(({e})=>!e.from||!e.to||e.regionId).map(({e,index})=>`<button type="button" data-map-leg="${index}"><span>${esc(e.from?.place.n||options.trip?.places?.[e.fromPlaceId]?.n||e.fromPlaceId)} → ${esc(e.to?.place.n||options.trip?.places?.[e.toPlaceId]?.n||e.toPlaceId)}</span><small>이동수단 · 시간 · 비용${!e.from||!e.to?' · 위치 미등록':''}</small></button>`).join('')}</details>`:''}
   ${m.flights.length||m.remoteEdges.length?`<div class="imap-flight-note"><b>✈ 항공·장거리 이동은 지역별로 분리</b><span>${m.flights.length?m.flights.map(x=>esc(x.title)).join(' · '):'떨어진 지역 사이의 이동'} · 자동차 경로로 연결하지 않습니다</span></div>`:''}
   ${m.missing.length?`<details class="imap-missing"><summary>위치 미등록 ${m.missing.length}회 · 지도에 표시하지 않았어요</summary>${m.missing.map(v=>`<button type="button" data-map-visit="${esc(v.id)}"><span class="imap-number">${v.number}</span><span>${esc(v.place.n)}<small>좌표 없음 · 일정에서 확인</small></span></button>`).join('')}</details>`:''}
   ${m.unlocatedCount?`<p class="imap-unlocated">장소가 지정되지 않은 일정 ${m.unlocatedCount}개는 아래 일정표에서 확인하세요</p>`:''}
   <div class="imap-live" role="status" aria-live="polite"></div>`;
  renderViewport();renderSelection();updateHotelReference();
 }
 function updateHotelReference(){const label=$('.imap-hotel-region');if(!label)return;const hp=model.pointMap.get(model.hotelPlaceId);label.textContent=!hp?'좌표 미등록 · 숙소 정보에서 주소 확인':hp.regionId!==regionId?'다른 지역에 있어요 · 숙소 보기로 이동':'모든 날짜의 기준 장소';}
 function pxy(ll,s){const p=project(ll);return {x:(p[0]-view.cx)/view.width*s.width+s.width/2,y:(p[1]-view.cy)/view.height*s.height+s.height/2};}
 function selectedEdge(e){if(!selectedId)return false;if(e.fromVisitId||e.toVisitId)return e.fromVisitId===selectedId||e.toVisitId===selectedId;const v=model.visits.find(v=>v.id===selectedId);return !!v&&(e.fromPlaceId===v.placeId||e.toPlaceId===v.placeId);}
 function renderViewport(){
  if(destroyed||!view)return;const s=size(),svg=$('.imap-svg'),g=region(),points=g?.points||[],groups=markerGroups(points);svg.setAttribute('viewBox',`0 0 ${s.width} ${s.height}`);
  const step=niceStep(view.width/5),startX=Math.floor((view.cx-view.width/2)/step)*step,startY=Math.floor((view.cy-view.height/2)/step)*step;let grid='';
  for(let x=startX;x<=view.cx+view.width/2;x+=step){const xx=(x-view.cx)/view.width*s.width+s.width/2;grid+=`<path d="M${xx.toFixed(1)} 0V${s.height}"/>`;}
  for(let y=startY;y<=view.cy+view.height/2;y+=step){const yy=(y-view.cy)/view.height*s.height+s.height/2;grid+=`<path d="M0 ${yy.toFixed(1)}H${s.width}"/>`;}
  const localEdges=model.edges.filter(e=>e.regionId===regionId&&e.from&&e.to),lines=localEdges.map(e=>{const a=pxy(e.from.coords,s),b=pxy(e.to.coords,s);return `<path class="imap-route-line ${selectedEdge(e)?'is-selected':''}" d="M${a.x.toFixed(2)} ${a.y.toFixed(2)}L${b.x.toFixed(2)} ${b.y.toFixed(2)}"/><path class="imap-route-hit" data-map-line="${model.edges.indexOf(e)}" d="M${a.x.toFixed(2)} ${a.y.toFixed(2)}L${b.x.toFixed(2)} ${b.y.toFixed(2)}"/>`;}).join('');
  svg.innerHTML=`<g class="imap-grid">${grid}</g><g>${lines}</g>`;
  let pinHTML=localEdges.map(e=>{const a=pxy(e.from.coords,s),b=pxy(e.to.coords,s),x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(Math.hypot(a.x-b.x,a.y-b.y)<70||x<25||x>s.width-25||y<35||y>s.height-68)return '';const index=model.edges.indexOf(e);return `<button type="button" class="imap-leg" style="left:${x}px;top:${y}px" data-map-leg="${index}" aria-label="${esc(e.from.place.n)}에서 ${esc(e.to.place.n)} 이동수단·시간·비용 보기"><span aria-hidden="true">↗</span></button>`;}).join('');
  const candidates=groups.map(group=>{const nums=group.visits.map(v=>v.number),text=nums.length?nums.slice(0,2).join('·')+(nums.length>2?' +'+(nums.length-2):''):group.isHotel?'⌂':'•',selected=group.visits.some(v=>v.id===selectedId);return {...pxy(group.coords,s),label:group.points.find(p=>p.isHotel)?.place.n||group.points[0].place.n,selected,isHotel:group.isHotel,hasVisits:!!group.visits.length,order:group.visits[0]?.number??Infinity,markerWidth:Math.max(48,Math.max(42,Array.from(text).reduce((n,c)=>n+(/[^\x00-\x7F]/.test(c)?14:9),0)+22+(group.isHotel?18:0))+(selected?10:0)),markerHeight:selected?52:48};}),labels=labelLayout(candidates,s.width,s.height,expanded);
  pinHTML+=groups.map((group,i)=>{const p=candidates[i],box=labels[i];if(p.x<-70||p.x>s.width+70||p.y<-70||p.y>s.height+70)return '';const nums=group.visits.map(v=>v.number),text=nums.length?nums.slice(0,2).join('·')+(nums.length>2?' +'+(nums.length-2):''):group.isHotel?'⌂':'•',selected=p.selected,label=p.label;return `<button type="button" class="imap-pin ${group.isHotel?'is-hotel':''} ${selected?'is-selected':''} ${nums.length?'':'is-waypoint'}" style="left:${p.x}px;top:${p.y}px" data-map-point="${esc(group.points[0].id)}" data-marker-width="${p.markerWidth}" data-marker-height="${p.markerHeight}" aria-label="${esc(titleForGroup(group))}" title="${esc(titleForGroup(group))}" aria-pressed="${selected}"><span class="imap-pin-dot">${group.isHotel?'<i aria-hidden="true">⌂</i>':''}${esc(text)}</span><span class="imap-pin-label" style="width:${box.width}px;max-width:${box.width}px;top:${box.top-p.y+24}px;left:50%;margin-left:${box.left+box.width/2-p.x}px" ${box.visible?'':'hidden'}>${esc(label)}</span></button>`;}).join('');
  $('.imap-pins').innerHTML=pinHTML;
  const ll=unproject([view.cx,view.cy]),metres=view.width*Math.cos(ll[0]*Math.PI/180)*70/s.width;$('.imap-scale').textContent=metres>=1000?(metres/1000).toFixed(metres>=10000?0:1)+' km':Math.round(metres/10)*10+' m';
  $('.imap-empty').hidden=!!points.length;if(online)renderOnlineLayers();
 }
 function niceStep(v){const power=10**Math.floor(Math.log10(Math.max(1,v))),n=v/power;return (n<2?1:n<5?2:5)*power;}
 function renderSelection(groupOverride=null){
  const selected=groupOverride?(groupOverride.visits.find(v=>v.id===selectedId)||groupOverride.visits[0]||null):model.visits.find(v=>v.id===selectedId),point=selected?model.pointMap.get(selected.placeId):null,group=groupOverride||(point?markerGroups(region()?.points||[]).find(g=>g.points.some(p=>p.id===point.id)):null),el=$('.imap-selection');
  if(!group&&!selected){el.innerHTML='<p>번호 핀을 누르면 같은 번호의 일정으로 연결돼요</p>';return;}
  const visits=group?.visits||[selected],placeId=selected?.placeId||group.points[0].id,p=model.pointMap.get(placeId)?.place||selected?.place;
  el.innerHTML=`<div class="imap-selected-title"><b>${esc(p?.n||'장소')}</b><button type="button" data-map-place="${esc(placeId)}" data-map-item="${esc(selected?.id||visits[0]?.id||'')}">장소 정보 ›</button></div>${visits.length?`<div class="imap-visit-picks">${visits.map(v=>`<button type="button" data-map-visit="${esc(v.id)}" aria-pressed="${v.id===selectedId}"><span class="imap-number">${v.number}</span><span>${esc(v.item.title)}</span></button>`).join('')}</div>`:'<p>이동 중 경유 장소</p>'}${model.edges.filter(e=>e.fromPlaceId===placeId||e.toPlaceId===placeId).length?`<details class="imap-connected-legs"><summary>이 장소의 이동 구간 보기</summary>${model.edges.filter(e=>e.fromPlaceId===placeId||e.toPlaceId===placeId).map(e=>`<button type="button" data-map-leg="${model.edges.indexOf(e)}">${esc(e.from?.place.n||e.fromPlaceId)} → ${esc(e.to?.place.n||e.toPlaceId)}<small>이동수단 · 시간 · 비용 보기</small></button>`).join('')}</details>`:''}`;
 }
 function setRegion(id,fit=true){if(!model.regions.some(g=>g.id===id))return;regionId=id;if(fit){const s=size();view=fitView(region().points,s.width,s.height);}$$('[data-map-region]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mapRegion===id)));updateHotelReference();renderViewport();if(online)fitOnline();}
 function fitAll(){if(!region())return;const s=size();view=fitView(region().points,s.width,s.height);renderViewport();if(online)fitOnline();setStatus('현재 지역의 전체 동선을 표시했어요.');}
 function selectVisit(id,config={}){const v=model.visits.find(v=>v.id===id);if(!v)return;selectedId=id;const p=model.pointMap.get(v.placeId);if(p&&p.regionId!==regionId)setRegion(p.regionId);if(p&&config.focus!==false){const s=size();view=focusView(view,p.coords,s.width,s.height);if(leaflet&&online)leaflet.setView(p.coords,Math.max(leaflet.getZoom(),16),{animate:false});}renderViewport();renderSelection();if(config.notify)options.onVisit?.(id,v.placeId);}
 function focusHotel(){if(!model.hotel)return;const p=model.pointMap.get(model.hotelPlaceId);if(p){if(p.regionId!==regionId)setRegion(p.regionId);selectedId=p.visits.find(v=>v.id===selectedId)?.id||p.visits[0]?.id||null;const s=size();view=focusView(view,p.coords,s.width,s.height);renderViewport();if(online)leaflet.setView(p.coords,Math.max(leaflet.getZoom(),16),{animate:false});renderSelection(markerGroups([p])[0]);setStatus('숙소 주변을 확대했어요. 전체 동선 버튼으로 하루 전체를 볼 수 있어요.');}else{setStatus('숙소 좌표가 없습니다. 저장된 주소를 확인하세요.');}options.onHotel?.(model.hotelPlaceId,{focusOnly:true});}
 function activatePoint(id){const p=model.pointMap.get(id);if(!p)return;const g=markerGroups(region()?.points||[]).find(g=>g.points.some(q=>q.id===id));if(g?.visits.length){const v=g.visits.find(v=>v.id===selectedId)||g.visits[0];selectedId=v.id;renderViewport();renderSelection(g);options.onVisit?.(v.id,v.placeId);}else{renderSelection(g);if(p.isHotel)options.onHotel?.(p.id,{focusOnly:false});else options.onPlace?.(p.id,null);}}
 function changeZoom(factor){if(online&&leaflet){leaflet.zoomIn(factor>1?1:-1);return;}view=zoomView(view,factor);renderViewport();}
 function expand(value=!expanded,{user=false}={}){if(value===expanded)return;expanded=value;if(value){lastFocus=doc.activeElement;placeholder=doc.createComment('itinerary-map-location');shell.parentNode.insertBefore(placeholder,shell);doc.body.appendChild(shell);oldOverflow=doc.body.style.overflow;doc.body.style.overflow='hidden';shell.classList.add('is-expanded');shell.setAttribute('role','dialog');shell.setAttribute('aria-modal','true');}else{shell.classList.remove('is-expanded');shell.removeAttribute('role');shell.removeAttribute('aria-modal');doc.body.style.overflow=oldOverflow;if(placeholder?.parentNode){placeholder.parentNode.insertBefore(shell,placeholder);placeholder.remove();}placeholder=null;lastFocus?.focus?.();options.onClose?.();}const b=$('[data-map-action="expand"]');b.textContent=value?'닫기':'⛶ 크게';b.setAttribute('aria-label',value?'지도 축소':'지도 크게 보기');if(value)b.focus();resize();options.onExpand?.(expanded,{user});}
 function resize(){if(destroyed)return;const s=size();if(view)view={...view,height:view.width*s.height/s.width};renderViewport();leaflet?.invalidateSize({pan:false});}
 function fitOnline(){const ps=region()?.points||[];if(!leaflet||!ps.length)return;leaflet.fitBounds(ps.map(p=>p.coords),{paddingTopLeft:[55,60],paddingBottomRight:[55,75],maxZoom:15,animate:false});}
 function renderOnlineLayers(){if(!online||!leaflet||!layerGroup)return;layerGroup.clearLayers();const L=root.L,ps=region()?.points||[];for(const e of model.edges.filter(e=>e.regionId===regionId&&e.from&&e.to)){const line=L.polyline([e.from.coords,e.to.coords],{color:selectedEdge(e)?'#1a619f':'#367eaa',weight:selectedEdge(e)?4:3,opacity:selectedEdge(e)?1:.65,dashArray:'3 8',interactive:true}).addTo(layerGroup);line.on('click',()=>options.onLeg?.(e));}
  for(const group of markerGroups(ps)){const ns=group.visits.map(v=>v.number),selected=group.visits.some(v=>v.id===selectedId),text=ns.length?ns.slice(0,2).join('·')+(ns.length>2?' +'+(ns.length-2):''):group.isHotel?'⌂':'•',html=`<span class="imap-pin-dot">${group.isHotel?'<i aria-hidden="true">⌂</i>':''}${esc(text)}</span>`;const marker=L.marker(group.coords,{icon:L.divIcon({className:`imap-leaflet-pin ${group.isHotel?'is-hotel':''} ${selected?'is-selected':''}`,html,iconSize:[48,48],iconAnchor:[24,24]}),keyboard:true,title:titleForGroup(group),alt:titleForGroup(group)}).addTo(layerGroup);marker.on('click',()=>activatePoint(group.points[0].id));}
 }
 async function enableOnline(){
  if(online){disableOnline();return;}if(onlineLoading)return;const token=++generation;onlineLoading=true;const b=$('[data-map-action="online"]');b.disabled=true;b.textContent='온라인 지도 불러오는 중…';setStatus('선택한 영역의 OpenStreetMap 배경지도를 불러옵니다.');
  try{const L=await loadLeaflet(doc);if(destroyed||token!==generation)return;online=true;onlineLoading=false;$('.imap-leaflet').hidden=false;shell.classList.add('has-online-map');leaflet=L.map($('.imap-leaflet'),{zoomControl:false,attributionControl:true,scrollWheelZoom:false,keyboard:true,preferCanvas:false});leaflet.attributionControl.setPrefix('<a href="https://leafletjs.com" target="_blank" rel="noopener">Leaflet</a>');
   tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,minZoom:2,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors',referrerPolicy:'origin',updateWhenIdle:true,keepBuffer:0,detectRetina:false});tileLayer.on('tileerror',()=>setStatus('일부 배경지도를 불러오지 못했습니다. 오프라인 동선도로 전환할 수 있어요.'));tileLayer.addTo(leaflet);layerGroup=L.layerGroup().addTo(leaflet);renderOnlineLayers();fitOnline();b.disabled=false;b.textContent='오프라인 동선도로 전환';b.setAttribute('aria-pressed','true');$('.imap-mode-note').textContent='OpenStreetMap · 인터넷 필요';$('.imap-corner-label').innerHTML='온라인 배경지도 <span>선은 방문 순서</span>';setStatus('온라인 배경지도를 켰어요. 점선은 실제 길찾기가 아닌 방문 순서입니다.');
  }catch(error){if(destroyed||token!==generation)return;disableOnline();const failed=$('.imap-leaflet'),fresh=doc.createElement('div');fresh.className='imap-leaflet';fresh.hidden=true;failed.replaceWith(fresh);b.disabled=false;b.textContent='온라인 배경지도 다시 켜기';setStatus((error.message||'배경지도를 불러오지 못했습니다.')+' 오프라인 동선도를 계속 사용할 수 있어요.');}
 }
 function disableOnline(){++generation;onlineLoading=false;online=false;try{leaflet?.remove();}catch(_){}leaflet=null;layerGroup=null;tileLayer=null;shell.classList.remove('has-online-map');$('.imap-leaflet').hidden=true;const b=$('[data-map-action="online"]');b.disabled=false;b.textContent='온라인 배경지도 켜기';b.setAttribute('aria-pressed','false');$('.imap-mode-note').textContent='기본 동선도는 인터넷 없이 사용';$('.imap-corner-label').innerHTML='오프라인 동선도 <span>저장된 좌표 기준</span>';renderViewport();setStatus('인터넷 없이 사용하는 동선도로 전환했어요.');}
 function click(e){if(Date.now()<ignoreClickUntil&&e.target.closest?.('.imap-pins,[data-map-line]'))return;const line=e.target.closest?.('[data-map-line]');if(line){options.onLeg?.(model.edges[Number(line.dataset.mapLine)]);return;}const el=e.target.closest?.('button');if(!el||!shell.contains(el))return;const d=el.dataset;if(d.mapRegion){setRegion(d.mapRegion);return;}if(d.mapPoint){activatePoint(d.mapPoint);return;}if(d.mapVisit){selectVisit(d.mapVisit,{notify:true});return;}if(d.mapPlace){options.onPlace?.(d.mapPlace,d.mapItem||null);return;}if(d.mapLeg!==undefined){options.onLeg?.(model.edges[Number(d.mapLeg)]);return;}
  switch(d.mapAction){case 'expand':expand(!expanded,{user:true});break;case 'zoom-in':changeZoom(1.6);break;case 'zoom-out':changeZoom(1/1.6);break;case 'fit':fitAll();break;case 'hotel':focusHotel();break;case 'hotel-info':options.onPlace?options.onPlace(model.hotelPlaceId,null):options.onHotel?.(model.hotelPlaceId,{focusOnly:false});break;case 'online':enableOnline();break;}
 }
 function keydown(e){if(e.key==='Escape'&&expanded){e.preventDefault();expand(false,{user:true});return;}if(expanded&&e.key==='Tab'){const els=$$('button:not([disabled]),a[href],[tabindex="0"]').filter(el=>!el.closest('[hidden]')&&el.getClientRects().length);if(els.length){const i=els.indexOf(doc.activeElement);if(e.shiftKey&&(i<=0)){e.preventDefault();els[els.length-1].focus();}else if(!e.shiftKey&&(i===els.length-1||i<0)){e.preventDefault();els[0].focus();}}}
  if(e.target!==$('.imap-stage')||online)return;const s=size(),delta={ArrowLeft:[55,0],ArrowRight:[-55,0],ArrowUp:[0,55],ArrowDown:[0,-55]}[e.key];if(delta){e.preventDefault();view=panView(view,...delta,s.width,s.height);renderViewport();}else if(['+','=','-','_'].includes(e.key)){e.preventDefault();changeZoom(['+','='].includes(e.key)?1.6:1/1.6);}else if(e.key==='Home'){e.preventDefault();fitAll();}}
 function gestureSnapshot(){const ps=[...pointers.values()];if(ps.length>=2)return {kind:'pinch',distance:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),mid:{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2},view:{...view}};if(ps.length)return {kind:'pan',start:ps[0],view:{...view}};return null;}
 function pointerDown(e){if(!online&&e.target.closest?.('.imap-stage'))e.stopPropagation();if(online||e.button>0||!e.target.closest?.('.imap-stage')||e.target.closest?.('.imap-mapbar,.imap-zoom'))return;const stage=$('.imap-stage'),r=stage.getBoundingClientRect();pointers.set(e.pointerId,{x:e.clientX-r.left,y:e.clientY-r.top});gesture=gestureSnapshot();dragged=false;if(!e.target.closest?.('button,[data-map-line]'))try{stage.setPointerCapture(e.pointerId);}catch(_){} }
 function pointerMove(e){if(!online&&e.target.closest?.('.imap-stage'))e.stopPropagation();if(!pointers.has(e.pointerId)||!gesture)return;const s=size(),r=$('.imap-stage').getBoundingClientRect();pointers.set(e.pointerId,{x:e.clientX-r.left,y:e.clientY-r.top});if(gesture.kind==='pinch'&&pointers.size>=2){const ps=[...pointers.values()],distance=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2};view=zoomView(gesture.view,distance/Math.max(1,gesture.distance),{x:gesture.mid.x/s.width,y:gesture.mid.y/s.height});view=panView(view,mid.x-gesture.mid.x,mid.y-gesture.mid.y,s.width,s.height);dragged=true;}else{const p=pointers.get(e.pointerId),dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.hypot(dx,dy)<5)return;view=panView(gesture.view,dx,dy,s.width,s.height);dragged=true;}e.preventDefault();try{$('.imap-stage').setPointerCapture(e.pointerId);}catch(_){}renderViewport();}
 function pointerUp(e){if(!online&&e.target.closest?.('.imap-stage'))e.stopPropagation();if(!pointers.has(e.pointerId))return;if(dragged)ignoreClickUntil=Date.now()+350;pointers.delete(e.pointerId);gesture=gestureSnapshot();try{$('.imap-stage').releasePointerCapture(e.pointerId);}catch(_){} }
 function update(next={}){if(destroyed)return;pointers.clear();gesture=null;dragged=false;ignoreClickUntil=0;const wasOnline=online,oldDay=options.dayId,oldRegion=regionId;options={...options,...next};if('selectedId'in next)selectedId=next.selectedId;model=buildModel(options.trip,options.dayId);if(!model.visits.some(v=>v.id===selectedId))selectedId=null;regionId=model.regions.some(g=>g.id===oldRegion)&&oldDay===options.dayId?oldRegion:model.defaultRegionId;if(wasOnline||onlineLoading)disableOnline();const s=shell.querySelector('.imap-stage')?size():{width:640,height:350};view=fitView(region()?.points||[],s.width,s.height);render();if(wasOnline)enableOnline();}
 function destroy(){if(destroyed)return;if(expanded)expand(false);destroyed=true;++generation;leaflet?.remove();resizeObserver?.disconnect();listeners.splice(0).forEach(fn=>fn());pointers.clear();shell.remove();}
 model=buildModel(options.trip,options.dayId);regionId=model.defaultRegionId;view=fitView(region()?.points||[]);render();listen(shell,'click',click);listen(shell,'keydown',keydown);listen(shell,'pointerdown',pointerDown);listen(shell,'pointermove',pointerMove,{passive:false});listen(shell,'pointerup',pointerUp);listen(shell,'pointercancel',pointerUp);listen(win,'resize',resize);
 if(win.ResizeObserver){resizeObserver=new win.ResizeObserver(resize);resizeObserver.observe(shell);}resize();
 return {update,destroy,selectVisit,fitAll,focusHotel,expand,disableOnline,getModel:()=>model,getState:()=>({regionId,selectedId,expanded,online,view:{...view}})};
}
return {create,buildModel,validCoords,coords,distanceKm,project,unproject,fitView,zoomView,panView,focusView,labelLayout,markerGroups,hotelId,flight};
});
