/* Read-only venue facts shared by itinerary and Places. No network/storage calls. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./place-reviews-data.js'));else root.TripPlaceReviews=factory(root.TripPlaceReviewData);})(typeof globalThis!=='undefined'?globalThis:this,function(defaultData){
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>typeof x==='string'?x.trim():'';
const excluded=new Set(['hotel','icn','tpe','lounge','a1','tms']);
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch(_){return null;}}
function dateOnly(value){const d=String(value||'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d?d:null;}
const identity=x=>text(x).toLowerCase().replaceAll('臺','台').replace(/[\s\p{P}\p{S}]/gu,'');
function create(data){
 const entries=new Map();for(const r of data?.places||[]){if(r&&typeof r.place_id==='string'&&!excluded.has(r.place_id)&&['restaurant','attraction'].includes(r.kind)&&text(r.name)&&!entries.has(r.place_id))entries.set(r.place_id,r);}
 const get=id=>entries.get(id)||null;
 function matches(r,place){if(!place)return true;const a=identity(r.address),b=identity(place.addr);if(a&&b)return a.includes(b)||b.includes(a);const names=[r.name,...(r.aliases||[])].map(identity),local=[place.n,place.zh].map(identity).filter(Boolean);return names.some(n=>n.length>=3&&local.some(p=>p.includes(n)||n.includes(p)));}
 function rating(r){const v=r?.rating;return v&&Number.isFinite(v.value)&&Number.isFinite(v.scale)&&v.scale>0&&v.value>=0&&v.value<=v.scale&&text(v.platform)&&text(String(v.count??''))&&safeURL(v.url)?v:null;}
 function ratingText(r){const v=rating(r);return v?v.platform+' '+v.value+'/'+v.scale+' · 후기 '+v.count+'건':'평점 미확인';}
 function link(url,label,cls=''){const href=safeURL(url);return href?`<a class="${esc(cls)}" href="${esc(href)}" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">${esc(label)} ↗</a>`:`<span>${esc(label)} · 출처 링크 미확인</span>`;}
 function localAlerts(r,dates=[]){
  const result=[],rule=r.opening_rule,closed=Array.isArray(rule?.closed_weekdays)?rule.closed_weekdays.filter(n=>Number.isInteger(n)&&n>=0&&n<=6):[];
  if(closed.length){const matches=[...new Set(dates.map(dateOnly).filter(Boolean))].filter(d=>closed.includes(new Date(d+'T12:00:00Z').getUTCDay()));const label=matches.length?matches.map(d=>d.slice(5).replace('-','/')+'('+['일','월','화','수','목','금','토'][new Date(d+'T12:00:00Z').getUTCDay()]+')').join(' · ')+' 방문 일정: ':'';result.push({text:label+r.name+' · '+(text(rule.closure_text)||text((r.alerts||[]).find(a=>closed.includes(a?.weekday))?.text)||closed.map(n=>['일','월','화','수','목','금','토'][n]+'요일').join('·')+' 휴관')+(r.place_id==='bopiliao'?' · 용산사 운영과 별도':''),source:rule.source||r.official_url,critical:matches.length>0});}
  for(const alert of r.alerts||[]){if(typeof alert==='string')result.push({text:alert,source:r.official_url});else if(text(alert?.text)&&!closed.includes(alert.weekday))result.push({text:alert.text,source:alert.source||alert.url||r.official_url,critical:alert.severity==='critical'});}
  return result;
 }
 function refs(item){if(!item||item.k!=='s')return [];const out=[];if(get(item.place))out.push(item.place);for(const r of entries.values()){const tokens=r.title_tokens||(r.place_id==='bopiliao'?['보피랴오','剝皮寮']:[]);if(tokens.some(t=>typeof t==='string'&&t.length>=3&&String(item.title||'').includes(t))&&!out.includes(r.place_id))out.push(r.place_id);}return out;}
 function teaser(id,place,options={}){const r=get(id);if(!r)return '';if(!matches(r,place))return `<span class="poi-card-teaser" data-poi-summary="${esc(id)}">조회 대상 주소 확인 필요</span>`;const alerts=localAlerts(r,options.dates),important=alerts.filter(a=>a.critical);return `<span class="poi-card-teaser" data-poi-summary="${esc(id)}">${esc(r.name)} · ${esc(ratingText(r))}<span class="poi-snapshot-label">${dateOnly(r.checked_at)?esc(dateOnly(r.checked_at))+' 웹 확인 · ':''}저장 정보 · 실시간 아님</span>${r.scope_note?'<span class="poi-scope-label">평가 대상 구분 · 상세에서 확인</span>':''}${important.map(a=>`<span class="poi-card-alert">${esc(a.text)}</span>`).join('')}</span>`;}
 function render(id,place,options={}){
  const r=get(id);if(!r)return '';const context=options.context||'place',same=matches(r,place),v=rating(r),checked=dateOnly(r.checked_at),alerts=localAlerts(r,options.dates),recommended=r.recommended||r.highlights||[],reviews=r.reviews||[];
  if(!same)return `<section class="poi-insight" data-poi="${esc(id)}" data-poi-context="${esc(context)}"><p class="poi-caution">저장한 장소와 조회 대상 주소가 달라 평점을 연결하지 않았어요.</p><p class="small">조회 대상: ${esc(r.name)} · ${esc(r.address||'주소 미확인')}</p>${link(r.official_url||r.rating?.url,'조회 대상 확인','btn smallbtn')}</section>`;
  const cautions=(r.cautions||[]).map(c=>typeof c==='string'?{text:c}:c).filter(c=>text(c?.text));
  return `<section class="poi-insight" data-poi="${esc(id)}" data-poi-context="${esc(context)}"><div class="poi-heading"><b>${r.kind==='restaurant'?'식당 평점·추천 메뉴':'볼거리·평점'}</b><span class="poi-rating" data-poi-rating>${esc(ratingText(r))}</span></div><p class="poi-identity" data-poi-identity>${esc(r.name)}${r.address?' · '+esc(r.address):''}</p><p class="poi-freshness" data-poi-freshness>${checked?esc(checked)+' 확인':'확인일 미기록'} · 저장한 웹 정보 · 실시간 아님</p>${r.scope_note?`<p class="poi-scope" data-poi-scope>${esc(r.scope_note)}</p>`:''}${r.match_note?`<p class="small">${esc(r.match_note)}</p>`:''}${v?.freshness?`<p class="small">${esc(v.freshness)}</p>`:r.rating_note?`<p class="small">${esc(r.rating_note)}</p>`:''}${alerts.map(a=>`<div class="poi-caution ${a.critical?'critical':''}" data-poi-alert><b>${esc(a.text)}</b>${link(a.source,'공식 운영 안내')}</div>`).join('')}<details class="poi-detail" ${options.open?'open':''}><summary>${r.kind==='restaurant'?'추천 메뉴·선별 후기':'볼거리·선별 후기'} · 주의사항</summary><div class="poi-detail-body">${r.opening_rule&&(r.opening_rule.hours||r.opening_rule.daily_hours||r.opening_rule.public_areas)?`<h4>운영 안내</h4><p>${esc(r.opening_rule.hours||r.opening_rule.daily_hours||'공용 공간 '+r.opening_rule.public_areas)}${r.opening_rule.shops_and_exhibitions?' · 점포·전시 '+esc(r.opening_rule.shops_and_exhibitions):''}</p>${r.opening_rule.exceptions?`<p class="small">${esc(r.opening_rule.exceptions)}</p>`:''}${link(r.opening_rule.source||r.official_url,'공식 운영 안내')}`:''}<h4>${r.kind==='restaurant'?'추천 메뉴':'볼거리'}</h4>${recommended.length?`<ul class="poi-recommendations">${recommended.map(m=>`<li><b>${esc(m.name||m.title)}</b><p>${esc(m.basis||m.description||'')}</p>${link(m.source||m.url,'추천 근거')}</li>`).join('')}</ul>`:'<p class="small">확인된 추천 자료가 아직 없어요.</p>'}<h4>선별 후기 요약</h4><p class="small">전체 후기의 대표성이나 방문일의 상태를 보장하지 않습니다.</p>${reviews.length?reviews.map(review=>`<article class="poi-review" data-poi-review><div><span class="poi-review-tone">${esc(({positive:'좋았던 점',mixed:'장단점',caution:'아쉬운 점',context:'대상·맥락 참고'})[review.sentiment]||'선별 후기')}</span><time>${dateOnly(review.date)?esc((review.date_type==='publication'?'게시 ':review.date_type==='visit'?'방문 ':'후기 날짜 ')+dateOnly(review.date)):'작성일 미확인'}</time></div><p>${esc(review.summary)}</p>${link(review.url,'후기 원문')}</article>`).join(''):'<p class="small">출처를 확인한 후기가 아직 없어요.</p>'}${cautions.length?`<h4>방문 전 확인</h4><ul class="poi-cautions">${cautions.map(c=>`<li>${esc(c.text)}${c.source||c.url?link(c.source||c.url,'근거'):''}</li>`).join('')}</ul>`:''}<p class="poi-disclaimer">${esc(data.notice||'저장한 공개 정보입니다. 영업·메뉴·가격은 방문 전에 다시 확인하세요.')}</p><div class="actions">${v?link(v.url,v.platform+' 평점 출처','btn smallbtn'):''}${r.official_url?link(r.official_url,'공식 안내','btn smallbtn'):''}</div></div></details></section>`;
 }
 return Object.freeze({get,refs,teaser,render,matches,ratingText,localAlerts,ids:()=>[...entries.keys()]});
}
return Object.freeze({...create(defaultData),create,safeURL,dateOnly});
});
