/* Durable local-only receipt intake. This module never submits an expense without explicit review. */
(function(root,factory){'use strict';const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.ReceiptQueue=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const MAX_SELECTION=20,ACTIVE=new Set(['queued','analyzing']),REVIEW=new Set(['review-ready','review-approved','failed','pending']);
const message=e=>String(e?.message||e||'처리를 완료하지 못했습니다.').slice(0,400);
function safeFields(raw={}){const f={};for(const k of ['date','time','merchant','currency','invoiceNumber','randomNumber','sellerTaxId','buyerTaxId','note'])f[k]=String(raw[k]??'').slice(0,k==='note'?1000:200);f.method=['card','cash','easy'].includes(raw.method)?raw.method:'card';f.total=raw.total!==null&&raw.total!==undefined&&raw.total!==''&&Number.isFinite(Number(raw.total))?Number(raw.total):null;return f;}
function create(options){
 const {store}=options,listeners=new Set();let running=null,intakeTail=Promise.resolve(),writeTail=Promise.resolve(),saveTail=Promise.resolve(),status={queued:0,analyzing:0,ready:0,approved:0,failed:0,recorded:0,remaining:0,intake:null,progress:null,error:null},resumeRequested=false,active=null,wakeAgain=false;
 const intakeReports=[];let intakeSerial=0;
 const now=()=>Date.now(),newId=()=> 'receipt-'+root.crypto.randomUUID(),getExpenses=()=>options.getExpenses?.()||[];
 const serialize=fn=>{const work=writeTail.then(fn,fn);writeTail=work.catch(()=>{});return work;};
 const update=(id,fn)=>serialize(async()=>{if(store.update)return store.update(id,fn);const r=await store.get(id);if(!r)return null;const next=fn(r);if(next)await store.put(next);return next||r;});
 const linked=r=>getExpenses().find(e=>e.receiptId===r.id||e.id===r.expenseId||e.receiptHash===r.imageHash||(r.invoiceKey&&e.receiptInvoiceKey===r.invoiceKey));
 function getStatus(){return {...status,intake:status.intake?{...status.intake,rejected:[...status.intake.rejected]}:null,progress:status.progress?{...status.progress}:null};}
 function emit(){const value=getStatus();for(const fn of listeners)try{fn(value);}catch(_){}try{options.onStatus?.(value);}catch(_){}}
 async function refresh(){const rows=await store.all(),counts={queued:0,analyzing:0,ready:0,approved:0,failed:0,recorded:0,remaining:0};for(const r of rows){if(r.trashedAt)continue;if(linked(r)){counts.recorded++;continue;}if(r.state==='queued')counts.queued++;else if(r.state==='analyzing')counts.analyzing++;else if(r.state==='failed')counts.failed++;else if(r.state==='review-approved')counts.approved++;else if(REVIEW.has(r.state)||r.state==='restored')counts.ready++;}counts.remaining=counts.queued+counts.analyzing+counts.ready+counts.approved+counts.failed;status={...status,...counts};emit();return rows;}
 function subscribeStatus(fn){listeners.add(fn);fn(getStatus());return ()=>listeners.delete(fn);}
 function reportIntake(report){status.intake=report;emit();}
 function enqueue(files){const selection=Array.from(files||[]),report={id:++intakeSerial,total:selection.length,processed:0,accepted:0,acceptedIds:[],rejected:[],done:false,current:''};intakeReports.push(report);if(intakeReports.length>5)intakeReports.shift();reportIntake(report);
  const work=intakeTail.then(async()=>{reportIntake(report);for(let i=0;i<selection.length;i++){const photo=selection[i],name=String(photo?.name||'사진 '+(i+1)).slice(0,200);report.current=name;reportIntake(report);try{if(i>=MAX_SELECTION)throw Error('한 번에 최대 20장까지 선택할 수 있습니다. 이 사진은 접수하지 않았습니다.');const size=await options.validateImage(photo),hash=await options.hashBlob(photo);await serialize(async()=>{const rows=await store.all();const duplicate=rows.find(r=>r.imageHash===hash)||getExpenses().find(e=>e.receiptHash===hash);if(duplicate)throw Error('같은 사진이 대기열·보관함·휴지통 또는 지출에 이미 있습니다. 다시 접수하지 않았습니다.');if(rows.length>=(options.maxRecords||500))throw Error('보관 한도 500장에 도달했습니다. 사진 포함 백업을 보관하세요.');const id=newId(),acceptedAt=Math.max(now(),...rows.map(r=>Number.isFinite(r.createdAt)?r.createdAt+1:0)),record={id,expenseId:'expense-'+id,createdAt:acceptedAt,updatedAt:acceptedAt,state:'queued',photo,imageHash:hash,width:size.width,height:size.height,filename:name,fields:safeFields(),text:'',warnings:[],reviewed:false,batchId:report.id};await store.add(record);report.accepted++;report.acceptedIds.push(id);});kick();}catch(e){report.rejected.push({name,index:i,message:options.storageMessage?.(e)||message(e)});}report.processed=i+1;reportIntake(report);await refresh().catch(e=>{status.error=message(e);emit();});}report.done=true;report.current='';reportIntake(report);kick();return {...report,acceptedIds:[...report.acceptedIds],rejected:[...report.rejected]};});intakeTail=work.catch(()=>{});return work;
 }
 async function analyzeOne(record){const runId=root.crypto.randomUUID(),ac=new AbortController();let claimed=false;await update(record.id,r=>{if(r.trashedAt||r.state!=='queued')return null;claimed=true;return {...r,state:'analyzing',runId,updatedAt:now(),error:null,reviewed:false};});if(!claimed)return;active={id:record.id,runId,controller:ac};status.progress={id:record.id,filename:record.filename,value:0,label:'기기에서 분석 준비 중'};await refresh();try{const result=await options.analyzeReceipt(record.photo,{signal:ac.signal,onProgress:p=>{if(active?.runId!==runId||ac.signal.aborted)return;status.progress={id:record.id,filename:record.filename,value:Number.isFinite(p?.progress)?Math.max(0,Math.min(1,p.progress)):0,label:typeof p==='string'?p:String(p?.status||'기기에서 분석 중').slice(0,90)};emit();}});await update(record.id,r=>{if(r.trashedAt||r.state!=='analyzing'||r.runId!==runId||ac.signal.aborted)return null;const fields=safeFields(result);if(fields.currency!=='TWD')fields.total=null;const next={...r,fields,text:String(result.text||'').slice(0,100000),warnings:(Array.isArray(result.warnings)?result.warnings:[]).slice(0,20).map(w=>options.warningText?.(w)||String(w).slice(0,200)),ocrConfidence:Number.isFinite(result.ocrConfidence)?result.ocrConfidence:null,state:'review-ready',updatedAt:now(),reviewed:false,error:null};delete next.runId;return next;});}catch(e){await update(record.id,r=>{if(r.trashedAt||r.state!=='analyzing'||r.runId!==runId)return null;const next={...r,state:'failed',error:message(e),updatedAt:now(),reviewed:false};delete next.runId;return next;});}finally{if(active?.runId===runId)active=null;status.progress=null;await refresh();}}
 async function drain(){if(resumeRequested){resumeRequested=false;const rows=await store.all();for(const row of rows){if(row.state==='analyzing'&&!row.trashedAt)await update(row.id,r=>r.state==='analyzing'?{...r,state:'queued',runId:null,updatedAt:now(),error:null}:null);if(row.state==='pending'&&linked(row))await update(row.id,r=>({...r,state:'recorded',updatedAt:now()}));}}for(;;){const rows=await refresh(),next=rows.filter(r=>r.state==='queued'&&!r.trashedAt).sort((a,b)=>a.createdAt-b.createdAt||a.id.localeCompare(b.id))[0];if(!next)break;await analyzeOne(next);}}
 function kick(){if(running){wakeAgain=true;return running;}const execute=()=>drain();running=(async()=>{if(root.navigator?.locks?.request){await root.navigator.locks.request('receipt-ocr:'+String(options.storageKey||'default'),{mode:'exclusive'},execute);}else await execute();})().catch(e=>{status.error=message(e);emit();}).finally(()=>{running=null;if(wakeAgain){wakeAgain=false;kick();}});return running;}
 async function resumeQueue(){resumeRequested=true;await refresh().catch(e=>{status.error=message(e);emit();});kick();return getStatus();}
 async function cancel(id){await update(id,r=>{if(!ACTIVE.has(r.state))return null;const next={...r,state:'failed',updatedAt:now(),error:'분석을 취소했습니다. 사진은 보관되어 있으며 직접 검토하거나 다시 분석할 수 있어요.',reviewed:false};delete next.runId;return next;});if(active?.id===id)active.controller.abort();await refresh();}
 async function retry(id){await update(id,r=>{if(r.trashedAt||linked(r)||ACTIVE.has(r.state))return null;return {...r,state:'queued',updatedAt:now(),reviewed:false,error:null};});await refresh();kick();}
 async function setTrashed(id,hidden){let changed;await update(id,r=>{changed={...r,updatedAt:now()};if(hidden){changed.trashedAt=now();if(ACTIVE.has(r.state)){changed.state='failed';changed.error='휴지통으로 옮겨 분석을 중단했습니다.';delete changed.runId;}}else delete changed.trashedAt;return changed;});if(hidden&&active?.id===id)active.controller.abort();await refresh();return changed;}
 async function saveDraft(id,raw){const fields=safeFields(raw);await update(id,r=>{if(r.trashedAt||linked(r)||ACTIVE.has(r.state))throw Error('분석 완료 후 보관함에 있는 미연결 영수증만 수정할 수 있습니다.');const next={...r,fields,reviewed:false,state:'review-ready',updatedAt:now(),error:null};delete next.invoiceKey;return next;});await refresh();}
 async function approve(id,raw,{reviewed=false,allowSimilar=false}={}){if(!reviewed)throw Error('사진과 날짜·상호·금액·결제수단을 먼저 확인해 주세요.');const fields=options.validateFields(raw);return serialize(async()=>{const rows=await store.all(),record=rows.find(r=>r.id===id);if(!record||record.trashedAt)throw Error('보관함에서 영수증을 찾지 못했습니다.');if(ACTIVE.has(record.state))throw Error('분석이 끝난 뒤 검토하거나 먼저 분석을 취소해 주세요.');if(linked(record))return record;const d=options.duplicates?.(rows,fields,record.imageHash,id)||{};if(d.strong)throw Error('같은 사진 또는 영수증 복권 번호가 이미 저장되어 있습니다.');if(d.weak&&!allowSimilar)throw Error('비슷한 기존 내역과 별개인지 확인해 주세요.');const approved={...record,fields,reviewed:true,allowSimilar:!!allowSimilar,state:'review-approved',updatedAt:now(),error:null};const key=options.invoiceKey(fields);if(key)approved.invoiceKey=key;else delete approved.invoiceKey;await store.put(approved);await refresh();return approved;});}
 function saveSelected(ids){const selected=[...new Set(ids||[])];const work=saveTail.then(async()=>{const result={saved:[],already:[],failed:[]};for(const id of selected){try{await serialize(async()=>{let record=await store.get(id);if(!record||record.trashedAt)throw Error('영수증이 없거나 휴지통에 있습니다.');if(linked(record)){result.already.push(id);if(record.state!=='recorded')await store.put({...record,state:'recorded'});return;}if(record.state!=='review-approved'||record.reviewed!==true)throw Error('원본과 비교한 검토가 아직 필요합니다.');const fields=options.validateFields(record.fields),rows=await store.all(),d=options.duplicates?.(rows,fields,record.imageHash,id)||{};if(d.strong)throw Error('같은 사진 또는 영수증 복권 번호가 이미 저장되어 있습니다.');if(d.weak&&!record.allowSimilar)throw Error('같은 날짜·상호·금액의 기존 지출을 다시 확인해 주세요.');record={...record,fields,state:'pending',updatedAt:now()};const preserved=record.expense&&Math.abs(record.expense.twd-fields.total)<.001?options.restoredExpense?.(record.expense,record):null;record.expense=preserved||options.expenseFrom(record,options.currentRate?.());await store.put(record);if(!options.addExpense)throw Error('지출 연결 기능이 준비되지 않았습니다.');await options.addExpense(record.expense);result.saved.push(id);try{await store.put({...record,state:'recorded',updatedAt:now(),error:null});}catch(_){/* Durable pending record is reconciled by stable expense identity after reload. */}});}catch(e){result.failed.push({id,message:options.storageMessage?.(e)||message(e)});await update(id,r=>linked(r)?{...r,state:'recorded'}:{...r,state:r.reviewed?'review-approved':r.state,error:message(e)}).catch(()=>{});}await refresh().catch(()=>{});}return result;});saveTail=work.catch(()=>{});return work;}
 return {enqueue,resumeQueue,getStatus,subscribeStatus,refresh,cancel,retry,setTrashed,saveDraft,approve,saveSelected,linked,intakeReports,async whenIdle(){await intakeTail;while(running)await running;await saveTail;},get activeId(){return active?.id||null;}};
}
return {create,safeFields,MAX_SELECTION,ACTIVE,REVIEW};
});
